version: "3.8"
services:
  movies:
    image: vickydoc094/movies:latest
    ports:
      - 81:80
    deploy:
      replicas: 3

  train:
    image: vickydoc094/train1:latest
    ports:
      - 82:80
    deploy:
      replicas: 3

  dth:
    image: vickydoc094/dth1:latest
    ports:
      - 83:80
    deploy:
      replicas: 3

  recharge:
    image: vickydoc094/recharge1:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
